# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='add_info',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
