# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_remove_ingredientsrecipes_addinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
