# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0005_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='addinfo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='menuapp.IngredientsRecipes', to='menuapp.Ingredient'),
        ),
    ]
