# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0006_auto_20171208_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
