# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0007_ingredientsrecipes_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
