# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0008_remove_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
