# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0009_auto_20171209_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
