# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0010_remove_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
