# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0011_auto_20171210_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuapp.Category'),
        ),
    ]
