# Generated by Django 2.0 on 2017-12-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0013_auto_20171217_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipes', models.ManyToManyField(to='menuapp.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='weeks',
            field=models.ManyToManyField(to='menuapp.Week'),
        ),
    ]
