# Generated by Django 2.0 on 2017-12-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0014_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeksRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.Recipe')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.Week')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='weeks',
            field=models.ManyToManyField(related_name='weeks', through='menuapp.WeeksRecipes', to='menuapp.Week'),
        ),
    ]
