# Generated by Django 2.0 on 2017-12-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0014_auto_20171218_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='recipes',
        ),
    ]
